Crear un script con el nombre "clase09_ej1.py" que reciba 3 parametros a elección, verificando que sean exactamente esa cantidad, y muestre como salida los parámetros recibidos

In [1]:
a=open("hm09ej1.py","w")
a.write("import sys\n")
a.close()


In [3]:

a=open("hm09ej1.py","a")
a.write("if len(sys.argv) == 4:\n")
a.write('    print("El primer parámetro es:",sys.argv[1])\n')
a.write('    print("El segundo parámetro es:",sys.argv[1])\n')
a.write('    print("El tercer parámetro es:",sys.argv[1])\n')


# else:
#     print("ERROR: Introdujo una cantidad de argumentos distinta de tres (3)")
#     print('Ejemplo: clase09_ej1.py 1 2 3')

49

In [4]:
a=open("ejemplo2.py","w")
a.close()

In [2]:
import os
lista_carpetas=os.listdir("./")


In [4]:
#print(lista_carpetas)
for i in lista_carpetas:
    print(i)

clase06_ej2.csv
clase09_ej1.py
clase09_ej2.csv
clase09_ej2.py
clase09_montañas_altas
colores.txt
ejemplo2.py
ejemplo_parametros.py
hm09ej1.py
hola.py
Prep_Course_Homework_09-Resuelto.ipynb
Prep_Course_Homework_09-Resuelto.py
Prep_Course_Homework_09.ipynb
Prep_Course_Homework_09.md
prueba.py
README.md
unejemplo.txt
__pycache__


In [5]:
os.getcwd()

'c:\\Users\\Marcelo\\Documents\\Henry\\Python-Prep\\M10_manejodearchivos'

In [1]:
import datetime

x = datetime.datetime.now()
print("Ahora =",x)
x = datetime.datetime(2020, 5, 10)
print("Fecha fija =",x)

fecha_hora = '2022-05-10 12:30:00.23555'
objeto_datetime = datetime.datetime.strptime(fecha_hora, '%Y-%m-%d %H:%M:%S')
marca_de_tiempo = datetime.datetime.timestamp(objeto_datetime)



Ahora = 2023-07-19 16:24:53.209121
Fecha fija = 2020-05-10 00:00:00
objeto datetime = 2022-05-10 12:30:00
timestamp = 1652196600.0
fecha hora = 2022-05-10 12:30:00


In [12]:

x = '2023-07-19 17:00:00'

marca_de_tiempo = datetime.datetime.timestamp(x)
print("timestamp =", marca_de_tiempo)

TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object

In [13]:
x = datetime.datetime.now()
x = int(datetime.datetime.timestamp(x))
print(x)

1689795621


In [19]:
x = datetime.datetime.now()
print(type(x))
x = (datetime.datetime.timestamp(x))
print(type(x))
print(x)
print(int(x))
print(type(int(x)))


<class 'datetime.datetime'>
<class 'float'>
1689797428.255422
1689797428
<class 'int'>


Crear un archivo a partir de los datos presentes en el diccionario provisto. El cual debe contener en la primera fila el nombre de las claves y luego cada línea los elementos i-ésimos de las listas de valores contiguos y separados por coma ','. Este archivo debe llamarse clase09_ej3.csv

nombre orden cordillera ...
everst, 1, Himalaya, Nepal, 8849



In [1]:
m = {'nombre':[  'Everest','K2','Kanchenjunga','Lhotse','Makalu',
                        'Cho Oyu','Dhaulagiri','Manaslu','Nanga Parbat','Annapurna I'],
            'orden':[1,2,3,4,5,6,7,8,9,10],
            'cordillera':['Himalaya','Karakórum','Himalaya','Himalaya','Himalaya'
                        ,'Himalaya','Himalaya','Himalaya','Karakórum','Himalaya'],
            'pais': ['Nepal','Pakistán','Nepal','Nepal','Nepal','Nepal','Nepal','Nepal',
                    'Pakistán','Nepal'],
            'altura':[8849,8611,8586,8516,8485,8188,8167,8163,8125,8091]}

In [2]:

c=0
guarda=""
for i in m.keys():
    c=c+1
    if c>1:
        guarda=guarda+", "+i
    else:
        guarda=i
a=open("am.csv","a")
a.write(guarda+"\n")
a.close()


In [3]:
zzz=zip(m)
print(zzz)
for i,x in enumerate(zzz):
    print(i)
    print(x)
    

0
('nombre',)
1
('orden',)
2
('cordillera',)
3
('pais',)
4
('altura',)


In [22]:
lista_nombre=m["altura"]
print(lista_nombre)

print(m["altura"][9])

[8849, 8611, 8586, 8516, 8485, 8188, 8167, 8163, 8125, 8091]
8091


In [32]:
a=open("am.csv","a")
for i in range(0,10):
    cadena=m["nombre"][i]+", "+str(m["orden"][i])+", "+m["cordillera"][i]+", "+m["pais"][i]+", "+str(m["altura"][i])
    #print(cadena)
    a.write(cadena+"\n")
a.close()    



In [40]:
import os
print(str(round(os.path.getsize('am.csv'),2)),'bytes')
print(str(round(os.path.getsize('am.csv')/1024,2)),'kilo bytes')
print(str(round(os.path.getsize('am.csv')/1024/1024,5)),'mega bytes')


410 bytes
0.4 kilo bytes
0.00039 mega bytes


In [42]:
print(str(os.path.getsize('am.csv')))

410


In [44]:
os.makedirs('clase09_ma')

In [45]:
os.system('copy am.csv clase09_ma')

0

In [46]:
os.listdir('./clase09_ma')

['am.csv']

In [47]:
os.listdir('./')

['am.csv',
 'clase06_ej2.csv',
 'clase09_ej1.py',
 'clase09_ej2.csv',
 'clase09_ej2.py',
 'clase09_ma',
 'clase09_montañas_altas',
 'colores.txt',
 'ejemplo2.py',
 'ejemplo_parametros.py',
 'hm09ej1.py',
 'hola.py',
 'Prep_Course_Homework_09-Resuelto.ipynb',
 'Prep_Course_Homework_09-Resuelto.py',
 'Prep_Course_Homework_09.ipynb',
 'Prep_Course_Homework_09.md',
 'prueba.py',
 'README.md',
 'unejemplo.txt',
 '__pycache__']

In [51]:
la=os.listdir()

In [58]:
for i in la:
    print(i+": "+(str(os.path.getsize(i)))+" bytes")
    

am.csv: 410 bytes
clase06_ej2.csv: 0 bytes
clase09_ej1.py: 390 bytes
clase09_ej2.csv: 811 bytes
clase09_ej2.py: 795 bytes
clase09_ma: 0 bytes
clase09_montañas_altas: 0 bytes
colores.txt: 93 bytes
ejemplo2.py: 376 bytes
ejemplo_parametros.py: 501 bytes
hm09ej1.py: 428 bytes
hola.py: 208 bytes
Prep_Course_Homework_09-Resuelto.ipynb: 13797 bytes
Prep_Course_Homework_09-Resuelto.py: 3361 bytes
Prep_Course_Homework_09.ipynb: 12887 bytes
Prep_Course_Homework_09.md: 2382 bytes
prueba.py: 135 bytes
README.md: 7801 bytes
unejemplo.txt: 44 bytes
__pycache__: 0 bytes


In [1]:
import numpy as np
v=np.arange(5)


In [3]:
print(v)
for i in v:
    print(i)

[0 1 2 3 4]
0
1
2
3
4


In [24]:
m16=np.arange(100,116).reshape(8,2)

In [25]:
print(m16)

[[100 101]
 [102 103]
 [104 105]
 [106 107]
 [108 109]
 [110 111]
 [112 113]
 [114 115]]


In [22]:
t=np.arange(24).reshape(2,3,4)
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
masqueuntensor=np.arange(240).reshape(2,3,4,10)
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
import numpy as np

In [8]:
my_first_vector = np.array([2, 5, 6, 23])
print(my_first_vector)


my_first_matrix = np.array([[2, 4,], [6, 8]])
print(my_first_matrix)

my_list = [0, 1, 2, 3, 4]
print(np.array(my_list))


[ 2  5  6 23]
[[2 4]
 [6 8]]
[0 1 2 3 4]


In [17]:
print(np.arange(10))
print(np.arange(5,10))
print(np.arange(5,10,2))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[5 7 9]


In [30]:
print(np.linspace(0,100,3))

[  0.  50. 100.]


In [31]:
print(np.random.rand(2, 2))

[[0.70879561 0.35307465]
 [0.67636755 0.69115262]]


In [77]:
print(np.random.rand(5))

[0.76269711 0.39710524 0.88695067 0.2801527  0.51147185]


In [80]:
print(np.random.uniform(5, 10, 10))

[9.87488768 5.29109217 5.53136788 6.98176991 9.26439124 9.92009654
 9.28303024 5.80549219 5.08190838 9.85646687]


In [97]:
print(np.random.normal(50, 10, 10))

[56.86807831 73.72616074 49.06492536 53.87434452 58.27660543 46.50249288
 53.53047212 51.07719581 51.43098291 49.05264221]


In [102]:
print(np.random.randint(1,3,100))

[2 2 1 1 1 1 1 2 1 1 2 1 1 2 2 1 2 2 1 2 2 2 2 1 2 1 2 1 1 2 2 1 1 1 1 1 1
 2 1 2 2 1 1 2 2 1 1 1 1 1 1 2 1 2 2 1 2 2 2 1 2 1 2 2 1 2 2 2 2 1 2 2 2 1
 1 2 2 2 2 1 1 1 1 1 2 1 2 2 2 2 2 1 2 1 2 2 1 1 2 2]


In [115]:
a=np.arange(11,15)
print(a)
print(a.dtype)
b=np.reshape(a, [2,2])
print(b)
print(b.dtype)
c=np.arange(100)
print(c.dtype)
f=np.reshape(c,[10,10])
print(f.dtype)

[11 12 13 14]
int32
[[11 12]
 [13 14]]
int32
int32
int32


In [120]:
a = np.arange(1,10)
print(a)
B = np.reshape(a, [3,3])
print(B)
print(B.dtype)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


In [121]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [122]:
vec=B.flatten()
print(vec)

[1 2 3 4 5 6 7 8 9]


In [144]:
otra = np.arange(9).reshape(3, 3)
print(otra)
# print(otra[1, 2])
#print(otra[-1, -1])
#print(otra[:, 1])
print(otra[:, 1:])
print(otra[0:2, 0:2])
print(otra[:, :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]
 [7 8]]
[[0 1]
 [3 4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np

In [19]:
B = np.full(4, 3,float)
C = np.ones((3,3))


print(C)




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a = np.array([[2,3],[2,3],[2,3]])
print(a)
b = np.array([[1,6,5,2,7],[1,2,7,0,9]])
print(b)
print(np.matmul(a,b))


print(a[0][1])



[[2 3]
 [2 3]
 [2 3]]
[[1 6 5 2 7]
 [1 2 7 0 9]]
[[ 5 18 31  4 41]
 [ 5 18 31  4 41]
 [ 5 18 31  4 41]]
3


In [22]:
a=(np.array([[1,2,3]]))
print(type(a))
b=(np.array([1,2,3]))
print(type(b))
m=(np.mat([1,2,3]))
print(type(m))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [31]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
m = np.mat([(1,2,3),(4,5,6)])
print(m)

a1=(a[:, 0])
print(a1)
print(type(a1))

m1=(m[:, 0])
print(m1)
print(type(m1))


print(a[:, 0].shape)

print(m[:, 0].shape)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 4]
<class 'numpy.ndarray'>
[[1]
 [4]]
<class 'numpy.matrix'>
(2,)
(2, 1)


In [34]:
height_list = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75]
print(np.mean(height_list))

print(np.median(height_list))

print(np.std(height_list))

print(np.percentile(height_list,50))


73.1923076923077
73.0
2.572326554954764
73.0


In [48]:
# Otras ufuncs interesantes
a = np.arange(4)
print(a)
b = np.arange(1,5)
print(b)

display((np.exp(a)) )        # exponencial
#array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])
print(np.log(b))         # logaritmo natural
#array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])
print(np.sqrt(a))        # raiz cuadrada
#array([ 0.        ,  1.        ,  1.41421356,  1.73205081])
print(np.greater(b,a))   # superior o igual punto a punto
#array([False, False, False, False], dtype=bool)

[0 1 2 3]
[1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229 1.38629436]
[0.         1.         1.41421356 1.73205081]
[ True  True  True  True]


In [41]:
print(np.log(20.09))

3.000222178826843


In [54]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for x in a:
    b[i] = x+x
    i+=1 
#296 ms ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

a = np.arange(1000000)
b = np.zeros(1000000)
b=a+a
#3.36 ms ± 275 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

298 ms ± 3.48 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
b=a+a

4.17 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
val1 = np.array([1, None, 2, 3])
print(val1)

val2 = np.array([1, np.nan, 3, 4])
print(val2)
print(np.mean(val2))

[1 None 2 3]
[ 1. nan  3.  4.]
nan


In [78]:
a = np.arange(0,20).reshape(2,10)

mascara = a>10
b=a[mascara]

zzz = b<15
print(b[zzz])



[11 12 13 14]
